### ISSUE TITLE
Question: Elasticsearch 5.0 support?

### ISSUE THREAD

**Issue by ilyanoskov** [codelibs/elasticsearch-taste#45]
Does this plugin support ES 5?

**Comment by gnujeremie** [comment]
Nice plugin, but really poor poor support and informations.

Would love to know too if es5 support is on the tracks.

**Comment by maystrovyy** [comment]
As far as I know - so far no support.

**Comment by gnujeremie** [comment]
I managed to install it on es 5.2, by modifying the plugin structure (following ES recommendations), but the _taste endpoint is not recognized when I try to PUT documents in my indices. It seems like there need to modify the plugin code.

**Comment by maystrovyy** [comment]
@gnujeremie yeap

**Comment by marevol** [comment]
For plugin specification, elasticsearch 5 does not have compatibility to 2.x.
I have no time to upgrade this plugin to elasticsearch 5.x plugin at the moment.
Any contributions are welcome.
Please contact [N2SM, Inc.](http://www.n2sm.net/en/) if you need commercial support.

**Comment by yehosef** [comment]
>I have no time to upgrade this plugin to elasticsearch 5.x plugin at the moment.
>Any contributions are welcome.

then you should leave the issue open.  The issue it not resolved - you just don't have time to work on it.  right now.
